packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^24.3.0
  '@antfu/utils': ^9.2.0
  '@vitejs/plugin-vue': ^5.2.3
  '@xiaohe01/eslint-config': ^1.5.1
  '@xiaohe01/tsconfig': ^1.0.4
  bumpp: ^10.1.0
  eslint: ^9.26.0
  esno: ^4.8.0
  lint-staged: ^15.5.1
  simple-git-hooks: ^2.13.0
  typescript: ~5.7.3
  unbuild: ^3.5.0
  vite: ^6.3.5
  vitest: ^3.1.3
  vue: ^3.5.13
  vue-tsc: ^2.2.10
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver