packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^24.2.0
  '@antfu/utils': ^9.1.0
  '@vitejs/plugin-vue': ^5.2.3
  '@xiaohe01/eslint-config': ^1.3.0
  '@xiaohe01/tsconfig': ^1.0.0
  bumpp: ^10.1.0
  eslint: ^9.22.0
  esno: ^4.8.0
  lint-staged: ^15.5.0
  simple-git-hooks: ^2.11.1
  typescript: ~5.7.3
  unbuild: ^3.5.0
  vite: ^6.2.2
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-tsc: ^2.2.8
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks