packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.0
    tsdown: ^0.13.0
    vite: ^7.0.5
  cli:
    bumpp: ^10.2.0
    pncat: ^0.2.6
  dev:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@xiaohe01/tsconfig': ^2.0.0
    typescript: ~5.7.3
    vue-tsc: ^3.0.3
  frontend:
    vue: ^3.5.18
  lint:
    '@xiaohe01/eslint-config': ^1.11.0
    eslint: ^9.31.0
    lint-staged: ^16.1.2
    simple-git-hooks: ^2.13.0
  prod:
    ress: ^5.0.2
  script:
    esno: ^4.8.0
  test:
    vitest: ^3.2.4
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks