ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.7
    tsdown: ^0.22.0
    vite: ^8.0.13
  cli:
    "@antfu/ni": ^30.1.0
    bumpp: ^11.1.0
    pncat: ^0.12.0
  frontend:
    "@vue/runtime-core": ^3.5.34
    vue: ^3.5.34
  lint:
    eslint: ^10.4.0
    lint-staged: ^17.0.5
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  style:
    ress: ^5.0.2
  test:
    vitest: ^4.1.7
  tsc:
    typescript: ~6.0.3
    vue-tsc: ~3.2.9
  types:
    "@types/node": ^24.12.4
  xiaohe:
    "@xiaohe01/catalog-rules": ^0.0.4
    "@xiaohe01/eslint-config": ^7.0.0
    "@xiaohe01/tsconfig": ^3.1.0

allowBuilds:
  esbuild: true
  simple-git-hooks: true