ignoreWorkspaceRootCheck: true
minimumReleaseAge: 0
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.8
    tsdown: ^0.22.14
    vite: ^8.2.2
  cli:
    "@antfu/ni": ^30.5.0
    bumpp: ^12.2.2
    pncat: ^0.13.2
  frontend:
    "@vue/runtime-core": ^3.5.42
    vue: ^3.5.42
  lint:
    eslint: ^10.9.1
    lint-staged: ^17.4.1
    simple-git-hooks: ^2.14.0
  script:
    esno: ^4.8.0
  style:
    ress: ^6.0.0
  test:
    vitest: ^4.1.11
  tsc:
    typescript: ~6.0.3
    vue-tsc: ~3.3.11
  types:
    "@types/node": ^24.13.3
  xiaohe:
    "@xiaohe01/catalog-rules": ^0.0.4
    "@xiaohe01/eslint-config": ^7.3.0
    "@xiaohe01/tsconfig": ^3.1.0

allowBuilds:
  esbuild: true
  simple-git-hooks: true