catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.2
    tsdown: ^0.17.1
    vite: ^7.2.7
  cli:
    "@antfu/ni": ^28.0.0
    bumpp: ^10.3.2
    pncat: ^0.7.7
  dev:
    "@vue/runtime-core": ^3.5.25
  frontend:
    ress: ^5.0.2
    vue: ^3.5.25
  lint:
    eslint: ^9.39.1
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  test:
    vitest: ^4.0.15
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.7
  types:
    "@types/node": ^22.19.1
  xiaohe:
    "@xiaohe01/eslint-config": ^4.0.1
    "@xiaohe01/tsconfig": ^3.0.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks