packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalog:
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@vitejs/plugin-vue': ^5.2.4
  '@xiaohe01/eslint-config': ^1.8.0
  '@xiaohe01/tsconfig': ^1.1.0
  bumpp: ^10.2.0
  eslint: ^9.29.0
  esno: ^4.8.0
  lint-staged: ^16.1.2
  ress: ^5.0.2
  simple-git-hooks: ^2.13.0
  typescript: ~5.7.3
  unbuild: ^3.5.0
  vite: ^6.3.5
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-tsc: ^2.2.10
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver