shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.5
    tsdown: ^0.21.4
    vite: ^8.0.1
  cli:
    "@antfu/ni": ^29.0.0
    bumpp: ^11.0.1
    pncat: ^0.11.0
  frontend:
    "@vue/runtime-core": ^3.5.30
    vue: ^3.5.30
  lint:
    eslint: ^10.0.3
    lint-staged: ^16.4.0
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  style:
    ress: ^5.0.2
  test:
    vitest: ^4.1.0
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.2.6
  types:
    "@types/node": ^24.12.0
  xiaohe:
    "@xiaohe01/catalog-rules": ^0.0.3
    "@xiaohe01/eslint-config": ^5.6.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks