packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.2
    tsdown: ^0.16.5
    vite: ^7.2.2
  cli:
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    pncat: ^0.7.6
  dev:
    "@vue/runtime-core": ^3.5.24
  frontend:
    vue: ^3.5.24
  lint:
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  prod:
    ress: ^5.0.2
  script:
    esno: ^4.8.0
  test:
    vitest: ^4.0.10
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.1.4
  types:
    "@types/node": ^22.19.1
  xiaohe:
    "@xiaohe01/eslint-config": ^4.0.0
    "@xiaohe01/tsconfig": ^3.0.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks