packages:
  - docs
  - playground
  - packages/**
  - examples/**
catalogs:
  build:
    '@vitejs/plugin-vue': ^6.0.1
    tsdown: ^0.15.6
    vite: ^7.1.9
  cli:
    '@antfu/ni': ^26.1.0
    bumpp: ^10.3.1
    pncat: ^0.6.1
  dev:
    '@vue/runtime-core': ^3.5.22
  frontend:
    vue: ^3.5.22
  lint:
    eslint: ^9.37.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
  prod:
    ress: ^5.0.2
  script:
    esno: ^4.8.0
  test:
    vitest: ^3.2.4
  tsc:
    typescript: ~5.8.3
    vue-tsc: ^3.1.1
  utils:
    '@antfu/utils': ^9.3.0
  xiaohe:
    '@xiaohe01/eslint-config': ^2.4.0
    '@xiaohe01/tsconfig': ^2.0.0
onlyBuiltDependencies:
  - esbuild
  - pncat
  - simple-git-hooks