shellEmulator: true
trustPolicy: no-downgrade

packages:
  - docs
  - playground
  - packages/**
  - examples/**

catalogs:
  build:
    "@vitejs/plugin-vue": ^6.0.4
    tsdown: ^0.20.3
    vite: ^7.3.1
  cli:
    "@antfu/ni": ^28.2.0
    bumpp: ^10.4.1
    pncat: ^0.10.2
  frontend:
    "@vue/runtime-core": ^3.5.29
    vue: ^3.5.29
  lint:
    eslint: ^9.39.3
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  script:
    esno: ^4.8.0
  style:
    ress: ^5.0.2
  test:
    vitest: ^4.0.18
  tsc:
    typescript: ~5.9.3
    vue-tsc: ^3.2.5
  types:
    "@types/node": ^24.10.14
  xiaohe:
    "@xiaohe01/catalog-rules": ^0.0.3
    "@xiaohe01/eslint-config": ^5.4.0
    "@xiaohe01/tsconfig": ^3.1.0

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks